<h1> Discovering Unusual Periodically Human Activity Patterns Through Fuzzy High Utility Rare Itemsets Mining </h1>

<h2> Abstract </h2>
Monitoring the resident activities is a key goal to build a safe and convenient environment in a smart house system. One way to capture the activity is by installing motion sensors around the house. By collecting the triggered sensor state, we attempt to find unusual activity patterns to notify suspicious movements or health issues information as our main goals. This study focuses to express the nature of time interval of each activity more clearly using fuzzy set. Next, this study employs fuzzy high utility rare itemsets mining to obtain some odd activities with different quantity of time intervals. Hence, we can determine how peculiar the activity. In this study, we analyzed the public human activity recognition dataset based on each single resident and their activities. As the results, we successfully catch the uncommon activity compared to the daily ones either fishy movements or sick, the illogical movement order, and the false alarm due to the limitation of sensor transmission.

<b>Keywords</b> : <i>Unusual Human Activity, Periodical Patterns, High Utility Itemsets, Fuzzy Itemsets.</i>

For more information, visit my paper URL : https://intip.in/J9Og

<h2>Import Database</h2>

This study uses secondary data which publicly available for download from https://sites.google.com/site/tim0306/datasets. We have pre-processing the data before and get 'database quantitative.csv'

In [10]:
import pandas as pd

database = pd.read_csv('database quantitative.csv',delimiter=';',index_col=0)
items=list(database)
items

['balkon deur,Brush Teeth,short',
 'balkon deur,Go to bed,short',
 'balkon deur,Use Toilet,short',
 'toilet flush,Use Toilet,short',
 'kwik cutlary drawer,Use Toilet,short',
 'balkon deur,Prepare brunch,short',
 'cupboard plates,Prepare brunch,short',
 'Toilet door,Prepare brunch,short',
 'balkon deur,Other Activity,short',
 'press bed links,Other Activity,short',
 'cupboard plates,Other Activity,short',
 'kwik dresser,Other Activity,short',
 'frontdoor,Other Activity,short',
 'balkon deur,Take Shower,short',
 'cupboard groceries,Take Shower,short',
 'balkon deur,Leaving the House,short',
 'cupboard groceries,Leaving the House,short',
 'press bed rechts,Leaving the House,short',
 'cupboard groceries,Other Activity,short',
 'press bed rechts,Other Activity,short',
 'dead,Other Activity,short',
 'toilet flush,Other Activity,short',
 'kwik cutlary drawer,Other Activity,short',
 'Other Sensor,Other Activity,short',
 'temp shower,Other Activity,short',
 'Toilet door,Other Activity,short',
 'kwik dresser,Get a drink,short',
 'Other Sensor,Prepare dinner,short',
 'dead,Prepare dinner,short',
 'cupboard plates,Prepare dinner,short',
 'kwik dresser,Prepare dinner,short',
 'frontdoor,Prepare dinner,short',
 'temp shower,Prepare dinner,short',
 'Toilet door,Prepare dinner,short',
 'dead,Get a drink,short',
 'kwik dresser,Use Toilet,short',
 'cupboard groceries,Go to bed,short',
 'toilet flush,Go to bed,short',
 'kwik cutlary drawer,Go to bed,short',
 'Other Sensor,Prepare brunch,short',
 'cupboard groceries,Use Toilet,short',
 'balkon deur,Get a drink,short',
 'cupboard groceries,Get a drink,short',
 'cupboard groceries,Brush Teeth,short',
 'toilet flush,Brush Teeth,short',
 'cupboard groceries,Prepare brunch,short',
 'balkon deur,Prepare dinner,short',
 'frontdoor,Get a drink,short',
 'toilet flush,Prepare brunch,short',
 'kwik cutlary drawer,Prepare brunch,short',
 'balkon deur,Leaving the House,long',
 'Drukmat bureaustoel (piano),Other Activity,short',
 'toilet flush,Leaving the House,short',
 'dead,Prepare brunch,short',
 'toilet flush,Take Shower,short',
 'toilet flush,Prepare dinner,short',
 'kwik cutlary drawer,Prepare dinner,short',
 'kwik dresser,Prepare brunch,short',
 'temp shower,Prepare brunch,short',
 'frontdoor,Prepare brunch,short',
 'Toilet door,Get a drink,short',
 'Toilet door,Use Toilet,short',
 'Toilet door,Brush Teeth,short',
 'Toilet door,Go to bed,short',
 'Toilet door,Take Shower,short',
 'Toilet door,Leaving the House,normal',
 'Toilet door,Leaving the House,long',
 'Toilet door,Leaving the House,short',
 'dead,Leaving the House,short',
 'cupboard groceries,Prepare dinner,short',
 'Other Sensor,Use Toilet,short',
 'Other Sensor,Go to bed,short',
 'kwik dresser,Brush Teeth,short',
 'kwik dresser,Go to bed,short',
 'kwik cutlary drawer,Take Shower,short']

<h2> Mining Fuzzy High Utility Rare Itemsets </h2>

Determine the support of each itemsets in database quantitative.csv

In [11]:
#find the activity != 0
hari=[]
ittems=[]
for k in range(24):
    for i in range(75):
        it1=database.iloc[k][items[i]]
        if it1!=0:
            ittems.append(items[i])
        elif it1==0:
            continue
    hari.append(ittems)
    ittems=[]

In [12]:
from itertools import combinations
gah=[]
for i in range(24):
    gac=list(combinations(hari[i],1))
    gah.extend(gac)
xr=[]
xf=[]

for team in [ele for ind, ele in enumerate(gah,1) if ele not in gah[ind:]]:
    count = 0
    for ele in gah:
        if team == ele:
            count += 1
    xr.append(team)
    xf.append(count)
    count = 0
data=pd.DataFrame(xr)
data['count']=xf
data

                                           0  count
0          kwik dresser,Other Activity,short      1
1             frontdoor,Other Activity,short      2
2          toilet flush,Other Activity,short      2
3   kwik cutlary drawer,Other Activity,short      2
4         balkon deur,Leaving the House,long      1
..                                       ...    ...
70  press bed rechts,Leaving the House,short     16
71        cupboard groceries,Go to bed,short     11
72              toilet flush,Go to bed,short     16
73       kwik cutlary drawer,Go to bed,short     13
74       cupboard groceries,Use Toilet,short     10

[75 rows x 2 columns]

Get Candidat 1-Rare itemset

In [13]:
e=max(data['count'])
a=min(data['count'])
selang=(e-a)/4
b=a+selang
c=b+selang
d=e-selang
#user provided threshold
thres=0.5
print(a,b,c,d,e)

1 5.5 10.0 14.5 19

In [14]:
t1=[] #very low support
t2=[] #low support
t3=[] #normal
t4=[] #high support
t5=[] #very high support

for j in range(len(data['count'])):
    angka=data['count'][j]
    if angka<=a:
        t1.append(1)
        t2.append(0)
        t3.append(0)
        t4.append(0)
        t5.append(0)
    elif a<angka<b:
        t1.append((b-angka)/(b-a))
        t2.append((angka-a)/(b-a))
        t3.append(0)
        t4.append(0)
        t5.append(0)
    elif angka==b:
        t1.append(0)
        t2.append(1)
        t3.append(0)
        t4.append(0)
        t5.append(0)
    elif b<angka<c:
        t1.append(0)
        t2.append((c-angka)/(c-b))
        t3.append((angka-b)/(c-b))
        t4.append(0)
        t5.append(0)
    elif angka==c:
        t1.append(0)
        t2.append(0)
        t3.append(1)
        t4.append(0)
        t5.append(0)
    elif c<angka<d:
        t1.append(0)
        t2.append(0)
        t3.append((d-angka)/(d-c))
        t4.append((angka-c)/(d-c))
        t5.append(0)
    elif angka==d:
        t1.append(0)
        t2.append(0)
        t3.append(0)
        t4.append(1)
        t5.append(0)
    elif d<angka<e:
        t1.append(0)
        t2.append(0)
        t3.append(0)
        t4.append((e-angka)/(e-d))
        t5.append((angka-d)/(e-d))
    elif angka>=e:
        t1.append(0)
        t2.append(0)
        t3.append(0)
        t4.append(0)
        t5.append(1)

data['very low']=t1
data['low']=t2
data['normal']=t3
data['high']=t4
data['very high']=t5

itemu=[]
verlo=[]
loo=[]
tt3=[]
tt4=[]
tt5=[]
tt6=[]

for i in range(75):
    if data['very low'][i]>=thres or data['low'][i]>=thres:
        itemu.append(data[0][i])
        verlo.append(data['very low'][i])
        loo.append(data['low'][i])
        tt3.append(data['normal'][i])
        tt4.append(data['high'][i])
        tt5.append(data['very high'][i])

dataa=pd.DataFrame(itemu)
dataa['very low']=verlo
dataa['low']=loo
dataa['normal']=tt3
dataa['high']=tt4
dataa['very high']=tt5
dataa

,0,very low,low,normal,high,very high
0,"kwik dresser,Other Activity,short",1.000000,0.000000,0.000000,0.0,0.0
1,"frontdoor,Other Activity,short",0.777778,0.222222,0.000000,0.0,0.0
2,"toilet flush,Other Activity,short",0.777778,0.222222,0.000000,0.0,0.0
3,"kwik cutlary drawer,Other Activity,short",0.777778,0.222222,0.000000,0.0,0.0
4,"balkon deur,Leaving the House,long",1.000000,0.000000,0.000000,0.0,0.0
5,"dead,Get a drink,short",0.333333,0.666667,0.000000,0.0,0.0
6,"dead,Prepare dinner,short",0.555556,0.444444,0.000000,0.0,0.0
7,"temp shower,Prepare dinner,short",0.333333,0.666667,0.000000,0.0,0.0
8,"frontdoor,Prepare brunch,short",1.000000,0.000000,0.000000,0.0,0.0
9,"Toilet door,Brush Teeth,short",1.000000,0.000000,0.000000,0.0,0.0
10,"Toilet door,Leaving the House,normal",1.000000,0.000000,0.000000,0.0,0.0
11,"Toilet door,Leaving the House,long",1.000000,0.000000,0.000000,0.0,0.0
12,"Toilet door,Go to bed,short",0.333333,0.666667,0.000000,0.0,0.0
13,"Toilet door,Get a drink,short",0.000000,0.888889,0.111111,0.0,0.0
14,"Toilet door,Use Toilet,short",0.000000,0.888889,0.111111,0.0,0.0
15,"Toilet door,Take Shower,short",0.111111,0.888889,0.000000,0.0,0.0
16,"Toilet door,Leaving the House,short",0.555556,0.444444,0.000000,0.0,0.0
17,"temp shower,Other Activity,short",0.555556,0.444444,0.000000,0.0,0.0
18,"press bed rechts,Other Activity,short",0.555556,0.444444,0.000000,0.0,0.0
19,"Other Sensor,Prepare brunch,short",0.333333,0.666667,0.000000,0.0,0.0
20,"dead,Leaving the House,short",1.000000,0.000000,0.000000,0.0,0.0
21,"press bed links,Other Activity,short",0.555556,0.444444,0.000000,0.0,0.0
22,"cupboard plates,Other Activity,short",0.333333,0.666667,0.000000,0.0,0.0
23,"cupboard groceries,Other Activity,short",0.000000,0.666667,0.333333,0.0,0.0
24,"dead,Other Activity,short",0.111111,0.888889,0.000000,0.0,0.0
25,"Toilet door,Prepare dinner,short",0.111111,0.888889,0.000000,0.0,0.0
26,"cupboard groceries,Get a drink,short",0.777778,0.222222,0.000000,0.0,0.0
27,"kwik cutlary drawer,Prepare brunch,short",0.555556,0.444444,0.000000,0.0,0.0
28,"Drukmat bureaustoel (piano),Other Activity,short",0.555556,0.444444,0.000000,0.0,0.0
29,"cupboard groceries,Prepare dinner,short",1.000000,0.000000,0.000000,0.0,0.0
30,"Other Sensor,Other Activity,short",0.333333,0.666667,0.000000,0.0,0.0
31,"Toilet door,Other Activity,short",0.111111,0.888889,0.000000,0.0,0.0
32,"Other Sensor,Use Toilet,short",1.000000,0.000000,0.000000,0.0,0.0
33,"Other Sensor,Go to bed,short",1.000000,0.000000,0.000000,0.0,0.0
34,"kwik dresser,Get a drink,short",0.777778,0.222222,0.000000,0.0,0.0
35,"Other Sensor,Prepare dinner,short",0.000000,0.888889,0.111111,0.0,0.0
36,"cupboard plates,Prepare dinner,short",0.333333,0.666667,0.000000,0.0,0.0
37,"kwik dresser,Prepare dinner,short",0.111111,0.888889,0.000000,0.0,0.0
38,"frontdoor,Prepare dinner,short",0.555556,0.444444,0.000000,0.0,0.0
39,"balkon deur,Get a drink,short",0.000000,0.888889,0.111111,0.0,0.0
40,"balkon deur,Prepare dinner,short",0.000000,0.888889,0.111111,0.0,0.0
41,"frontdoor,Get a drink,short",0.333333,0.666667,0.000000,0.0,0.0
42,"toilet flush,Prepare dinner,short",0.777778,0.222222,0.000000,0.0,0.0
43,"kwik cutlary drawer,Prepare dinner,short",0.777778,0.222222,0.000000,0.0,0.0
44,"kwik dresser,Use Toilet,short",0.555556,0.444444,0.000000,0.0,0.0
45,"toilet flush,Prepare brunch,short",0.333333,0.666667,0.000000,0.0,0.0
46,"toilet flush,Leaving the House,short",0.555556,0.444444,0.000000,0.0,0.0
47,"kwik dresser,Prepare brunch,short",0.777778,0.222222,0.000000,0.0,0.0
48,"kwik dresser,Brush Teeth,short",1.000000,0.000000,0.000000,0.0,0.0
49,"kwik dresser,Go to bed,short",1.000000,0.000000,0.000000,0.0,0.0
50,"toilet flush,Brush Teeth,short",0.555556,0.444444,0.000000,0.0,0.0
51,"cupboard groceries,Prepare brunch,short",0.555556,0.444444,0.000000,0.0,0.0
52,"dead,Prepare brunch,short",0.555556,0.444444,0.000000,0.0,0.0
53,"toilet flush,Take Shower,short",0.555556,0.444444,0.000000,0.0,0.0
54,"kwik cutlary drawer,Take Shower,short",1.000000,0.000000,0.000000,0.0,0.0
55,"cupboard groceries,Brush Teeth,short",0.000000,0.666667,0.333333,0.0,0.0
56,"temp shower,Prepare brunch,short",0.777778,0.222222,0.000000,0.0,0.0

In [15]:
candidat=[]
for i in range(56):
    candidat.append(dataa[0][i])

In [16]:
#get candidat each day
hari=[]
ittems=[]
for k in range(24):
    for i in range(56):
        it1=database.iloc[k][candidat[i]]
        if it1!=0:
            ittems.append(candidat[i])
        elif it1==0:
            continue
    hari.append(ittems)
    ittems=[]

Loop to get high utility rare itemset

In [17]:
import numpy as np

datareal=pd.DataFrame
columnes=[*range(0,8),'very low support','low support','normal support','high support','very high support','very low utility','low utility','normal utility','high utility','very high utility']
datareal=pd.DataFrame(columns=columnes)
datareal

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, very low support, low support, normal support, high support, very high support, very low utility, low utility, normal utility, high utility, very high utility]
Index: []

In [19]:
from itertools import combinations

for p in range(2,9):
    gah=[]
    utill=[]
    for i in range(24):
        gac=list(combinations(hari[i],p))
        gah.extend(gac)
    xr=[]
    xf=[]

    for team in [ele for ind, ele in enumerate(gah,1) if ele not in gah[ind:]]:
        count = 0
        for ele in gah:
            if team == ele:
                count += 1
        xr.append(team)
        xf.append(count)
        count = 0
    df=pd.DataFrame(xr)
    df['count']=xf
    summ=0
    uyt=[]
    for i in range(len(df)):
        for j in range(24):
            for k in range(p):
                if database.iloc[j][df[k][i]]==0:
                    break
                else: summ=summ+database.iloc[j][df[k][i]]
        uyt.append(summ)
        summ=0
    df['utility']=uyt
    
    e=max(df['count'])
    a=min(df['count'])
    selang=(e-a)/4
    b=a+selang
    c=b+selang
    d=e-selang
    #user provided threshold
    thres=0.5

    ee=max(df['utility'])
    aa=min(df['utility'])
    seelang=(ee-aa)/4
    bb=aa+selang
    cc=bb+selang
    dd=ee-selang
    #user provided threshold
    thresu=0.4

    t1=[] #very low support
    t2=[] #low support
    t3=[] #normal
    t4=[] #high support
    t5=[] #very high support

    for j in range(len(df['count'])):
        angka=df['count'][j]
        if angka<=a:
            t1.append(1)
            t2.append(0)
            t3.append(0)
            t4.append(0)
            t5.append(0)
        elif a<angka<b:
            t1.append((b-angka)/(b-a))
            t2.append((angka-a)/(b-a))
            t3.append(0)
            t4.append(0)
            t5.append(0)
        elif angka==b:
            t1.append(0)
            t2.append(1)
            t3.append(0)
            t4.append(0)
            t5.append(0)
        elif b<angka<c:
            t1.append(0)
            t2.append((c-angka)/(c-b))
            t3.append((angka-b)/(c-b))
            t4.append(0)
            t5.append(0)
        elif angka==c:
            t1.append(0)
            t2.append(0)
            t3.append(1)
            t4.append(0)
            t5.append(0)
        elif c<angka<d:
            t1.append(0)
            t2.append(0)
            t3.append((d-angka)/(d-c))
            t4.append((angka-c)/(d-c))
            t5.append(0)
        elif angka==d:
            t1.append(0)
            t2.append(0)
            t3.append(0)
            t4.append(1)
            t5.append(0)
        elif d<angka<e:
            t1.append(0)
            t2.append(0)
            t3.append(0)
            t4.append((e-angka)/(e-d))
            t5.append((angka-d)/(e-d))
        elif angka>=e:
            t1.append(0)
            t2.append(0)
            t3.append(0)
            t4.append(0)
            t5.append(1)

    df['very low support']=t1
    df['low support']=t2
    df['normal support']=t3
    df['high support']=t4
    df['very high support']=t5

    itemus=[]
    itemus2=[]
    verlos=[]
    loos=[]
    tt3s=[]
    tt4s=[]
    tt5s=[]
    tt6s=[]

    for i in range(len(df['count'])):
        if df['very low support'][i]>=thres or df['low support'][i]>=thres:
            for l in range(p):
                itemus.append(df[l][i])
            itemus2.append(itemus)
            itemus=[]
            verlos.append(df['very low support'][i])
            loos.append(df['low support'][i])
            tt3s.append(df['normal support'][i])
            tt4s.append(df['high support'][i])
            tt5s.append(df['very high support'][i])
            tt6s.append(df['utility'][i])
        
    df=pd.DataFrame(itemus2)
    df['very low support']=verlos
    df['low support']=loos
    df['normal support']=tt3s
    df['high support']=tt4s
    df['very high support']=tt5s
    df['utility']=tt6s

    t1=[] #very low utility
    t2=[] #low utility
    t3=[] #normal utility
    t4=[] #high utility
    t5=[] #very high utility

    for j in range(len(df['utility'])):
        aangka=df['utility'][j]
        if aangka<=aa:
            t1.append(1)
            t2.append(0)
            t3.append(0)
            t4.append(0)
            t5.append(0)
        elif aa<aangka<bb:
            t1.append((bb-aangka)/(bb-aa))
            t2.append((aangka-aa)/(bb-aa))
            t3.append(0)
            t4.append(0)
            t5.append(0)
        elif aangka==bb:
            t1.append(0)
            t2.append(1)
            t3.append(0)
            t4.append(0)
            t5.append(0)
        elif bb<aangka<cc:
            t1.append(0)
            t2.append((cc-aangka)/(cc-bb))
            t3.append((aangka-bb)/(cc-bb))
            t4.append(0)
            t5.append(0)
        elif aangka==cc:
            t1.append(0)
            t2.append(0)
            t3.append(1)
            t4.append(0)
            t5.append(0)
        elif cc<aangka<dd:
            t1.append(0)
            t2.append(0)
            t3.append((dd-aangka)/(dd-cc))
            t4.append((aangka-cc)/(dd-cc))
            t5.append(0)
        elif aangka==dd:
            t1.append(0)
            t2.append(0)
            t3.append(0)
            t4.append(1)
            t5.append(0)
        elif dd<aangka<ee:
            t1.append(0)
            t2.append(0)
            t3.append(0)
            t4.append((ee-aangka)/(ee-dd))
            t5.append((aangka-dd)/(ee-dd))
        elif aangka>=ee:
            t1.append(0)
            t2.append(0)
            t3.append(0)
            t4.append(0)
            t5.append(1)

    df['very low utility']=t1
    df['low utility']=t2
    df['normal utility']=t3
    df['high utility']=t4
    df['very high utility']=t5

    itemu=[]
    itemu2=[]
    verlo=[]
    vlos=[]
    los=[]
    nos=[]
    hos=[]
    vhos=[]
    loo=[]
    tt3=[]
    tt4=[]
    tt5=[]

    for i in range(len(df['utility'])):
        if df['high utility'][i]>=thresu or df['very high utility'][i]>=thresu:
            for l in range(p):
                itemu.append(df[l][i])
            itemu2.append(itemu)
            itemu=[]
            vlos.append(df['very low support'][i])
            los.append(df['low support'][i])
            nos.append(df['normal support'][i])
            hos.append(df['high support'][i])
            vhos.append(df['very high support'][i])
            verlo.append(df['very low utility'][i])
            loo.append(df['low utility'][i])
            tt3.append(df['normal utility'][i])
            tt4.append(df['high utility'][i])
            tt5.append(df['very high utility'][i])

    dataa=pd.DataFrame(itemu2)
    dataa['very low support']=vlos
    dataa['low support']=los
    dataa['normal support']=nos
    dataa['high support']=hos
    dataa['very high support']=vhos
    dataa['very low utility']=verlo
    dataa['low utility']=loo
    dataa['normal utility']=tt3
    dataa['high utility']=tt4
    dataa['very high utility']=tt5
    datareal=datareal.append(dataa, ignore_index=True)
datareal

,0,1,2,3,4,5,6,7,very low support,low support,normal support,high support,very high support,very low utility,low utility,normal utility,high utility,very high utility
0,"kwik dresser,Other Activity,short","frontdoor,Other Activity,short",NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.398981,0.601019,0
1,"kwik dresser,Other Activity,short","toilet flush,Other Activity,short",NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.412564,0.587436,0
2,"kwik dresser,Other Activity,short","kwik cutlary drawer,Other Activity,short",NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.419355,0.580645,0
3,"kwik dresser,Other Activity,short","dead,Get a drink,short",NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.439728,0.560272,0
4,"kwik dresser,Other Activity,short","dead,Prepare dinner,short",NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.344652,0.655348,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254337,"kwik dresser,Prepare dinner,short","frontdoor,Prepare dinner,short","balkon deur,Get a drink,short","balkon deur,Prepare dinner,short","frontdoor,Get a drink,short","toilet flush,Prepare dinner,short","kwik dresser,Use Toilet,short","toilet flush,Prepare brunch,short",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.443073,0.556927,0
254338,"kwik dresser,Prepare dinner,short","frontdoor,Prepare dinner,short","balkon deur,Get a drink,short","balkon deur,Prepare dinner,short","frontdoor,Get a drink,short","kwik cutlary drawer,Prepare dinner,short","kwik dresser,Use Toilet,short","toilet flush,Prepare brunch,short",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.448560,0.551440,0
254339,"kwik dresser,Prepare dinner,short","frontdoor,Prepare dinner,short","balkon deur,Get a drink,short","balkon deur,Prepare dinner,short","toilet flush,Prepare dinner,short","kwik cutlary drawer,Prepare dinner,short","kwik dresser,Use Toilet,short","toilet flush,Prepare brunch,short",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.443073,0.556927,0
254340,"kwik dresser,Prepare dinner,short","frontdoor,Prepare dinner,short","balkon deur,Prepare dinner,short","frontdoor,Get a drink,short","toilet flush,Prepare dinner,short","kwik cutlary drawer,Prepare dinner,short","kwik dresser,Use Toilet,short","toilet flush,Prepare brunch,short",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.470508,0.529492,0
254341,"kwik dresser,Prepare dinner,short","balkon deur,Get a drink,short","balkon deur,Prepare dinner,short","frontdoor,Get a drink,short","toilet flush,Prepare dinner,short","kwik cutlary drawer,Prepare dinner,short","kwik dresser,Use Toilet,short","toilet flush,Prepare brunch,short",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.294925,0.705075,0

Save the data frame

In [20]:
datareal.to_csv('thres 0.5.csv')